# Generated by Django 3.1.7 on 2021-03-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('todo_text', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
